# Name : Shaikh Abdul Sami
# RollNo : PIAIC114471
# Course : AIC
# Batch : 07

# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.shape(x)

(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print("============")
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']


7. Print the dimension of the array in question 3


In [7]:
x.ndim

1

8. Create a boolean array with all the True values

In [8]:
np.full((5,) , True , dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [10]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
x = np.arange(10)
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
y = np.zeros(10)
y[5] = 1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
y = np.random.randn(3,3)
y

array([[ 2.13887935,  0.85311032, -1.93373071],
       [ 0.06370363, -1.89864328, -2.16535027],
       [ 0.67366933,  0.81631041,  1.72242255]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr3 = arr1*arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
np.greater(arr1 , arr2)

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
a = np.arange(10)
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr = np.ones((12, 12))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
x = np.arange(10).reshape(2,5)
print("Original Array" , x)
x[0]

Original Array [[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
y = np.arange(10).reshape(2,5)
print("Original Array" , y)
y[1][1]

Original Array [[0 1 2 3 4]
 [5 6 7 8 9]]


6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
y = np.arange(10).reshape(2,5)
print(y)
y[0:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr1 = np.random.randn(100).reshape(10,10)
print("Array" , arr1)
maximum = arr1.max()
print("Maximum Value" , maximum)
minimum = arr1.min()
print("Minimum Value" , minimum)

Array [[-6.60612071e-01  5.11109997e-01  1.64568656e+00  1.04766039e+00
  -4.94676851e-01  1.71701673e+00  4.81258140e-01  1.79921443e+00
  -2.82564291e-02  3.87342179e-01]
 [-1.06327633e-01  2.09459033e+00  2.32044419e+00 -1.09378575e+00
  -6.27513265e-01 -2.48812385e+00 -1.54037300e+00 -7.69629138e-01
   1.65464728e-01 -5.66015631e-01]
 [-1.02970185e+00 -3.33841759e+00 -1.20703236e+00  2.15299757e-01
  -4.16315521e-01 -1.79500170e-01  7.47834033e-01  2.30887462e+00
  -2.99744292e-01  1.93477026e+00]
 [-1.41085969e+00  7.56434208e-01 -4.70416458e-01  1.41901421e+00
   9.14209829e-01  3.46083177e-01  9.88336207e-01 -1.42320845e-01
  -6.04781641e-01  5.94786723e-01]
 [-1.56289674e-01  2.10843641e+00 -1.56872698e+00 -1.43656517e+00
   2.09086720e-02 -2.57405227e-03  7.26874967e-01  7.80908045e-01
  -4.81241114e-01  1.74582726e+00]
 [ 1.70669678e+00 -1.19783765e+00 -6.69295378e-01 -8.64022610e-01
   7.28893016e-02 -3.17033886e-01  2.83926907e-02 -3.22508155e-01
  -1.62849034e+00 -1.009082

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4 )
data = data.astype(np.int64)
value = np.where(names[data] != 'Will')
value

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
        6, 6, 6, 6]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 1, 2, 3, 0, 1, 3, 0, 1, 2, 3, 0, 1, 2, 3,
        0, 1, 2, 3]))

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4 )
data = data.astype(np.int64)
value = np.where((names[data] != "Will") & (names[data] != "Joe"))
value

(array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 0, 2, 0, 1, 0, 2, 3]))

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr2d = np.random.uniform(low=1.0, high=15.0, size=(5,3))
arr2d

array([[14.16489989, 12.8998348 ,  5.25381583],
       [10.75985098,  5.02107242, 13.1107486 ],
       [ 5.68307889,  1.78959887,  4.64060947],
       [14.27595243,  2.18086821,  8.90177983],
       [10.90881426, 10.3428485 ,  8.98882774]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr = np.random.uniform(low=1.0, high=16.0, size=(2,2,4))
arr

array([[[13.21021379,  2.12038591,  2.46684479,  4.96438305],
        [11.66137182, 10.55372817,  3.30791028, 13.64810358]],

       [[ 7.88143018,  1.48840423,  5.18395062,  2.29436155],
        [13.21280783,  8.21604619,  7.54650985, 15.58828783]]])

33. Swap axes of the array you created in Question 32

In [33]:
np.swapaxes(arr,0,1)

array([[[13.21021379,  2.12038591,  2.46684479,  4.96438305],
        [ 7.88143018,  1.48840423,  5.18395062,  2.29436155]],

       [[11.66137182, 10.55372817,  3.30791028, 13.64810358],
        [13.21280783,  8.21604619,  7.54650985, 15.58828783]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.arange(10)
print("Array" ,arr)
arr_sqrt = np.sqrt(arr)
print("Square" , arr_sqrt)
arr_sqrt[arr_sqrt<0.5] = 0
arr_sqrt

Array [0 1 2 3 4 5 6 7 8 9]
Square [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [37]:
import random
arr1 = np.random.randint(12, size=random.randrange(0, 12))
arr2 = np.random.randint(12, size=random.randrange(0, 12))
print(arr1)
print(arr2)
np.where(arr1 == arr2)


[2 1]
[10]


(array([], dtype=int64),)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)




array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [39]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [40]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray = np.delete(sampleArray , 1, axis = 1) 
newColumn = np.array([[10,10,10]])
sampleArray = np.insert(sampleArray , 1, newColumn, axis = 1) 
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [41]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z= x.dot(y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [42]:
m=np.random.randn(20)
m.cumsum()

array([-1.2059423 , -0.40909822,  0.91501238,  0.38246246, -0.69883668,
       -1.45991551, -3.22528945, -4.37711782, -3.92459556, -4.89172802,
       -6.18680462, -5.56715498, -5.61948157, -5.37004281, -5.11883797,
       -5.58264467, -5.81302028, -6.05387613, -6.4294148 , -5.7908881 ])